### ISSUE TITLE
math detail

### ISSUE THREAD

**Issue by kassasin** [Rhoban/placo#3]
Is there any math detail?for example ,how to get relative orientation task jacobian in kinetic and dynamic problem?

**Comment by kassasin** [comment]
maybe some papers or books?

**Comment by Gregwar** [comment]
Hello,

What you want is likely to understand better the Lie theory. As a disclaimer, I am not myself an expert of it. I might spend some time writing the derivations needed in PlaCo in the future.

I would recommend Modern Robotics as an introduction reading: https://hades.mech.northwestern.edu/index.php/Modern_Robotics

Even if they don't provide very advanced derivations, they give a good introduction to twists and Jacobian, with most useful identities. I believe the advanced absolute reference would then be the works from Roy Featherstone, but you will need to invest more time to dive into it.

-----

If I understand well, your question is more about how to compute the relevant terms using the underlying rigid body library (in our case Pinocchio) ?
Do you want me to provide details about relative orientation in particular ?

**Comment by kassasin** [comment]
First of all, thank you very much for your reply. In fact, I have already studied Modern Robotics, but I am still a little far from understanding the content of Placo. Maybe I need to learn something else. If you have time, can you write some blogs to introduce the relevant calculations?for example relative_position_task,and relative_orientation_task.
`void RelativeOrientationTask::update()
{
  auto T_world_a = solver->robot.get_T_world_frame(frame_a);
  auto T_world_b = solver->robot.get_T_world_frame(frame_b);
  auto T_a_b = T_world_a.inverse() * T_world_b;

  Eigen::Vector3d error = pinocchio::log3(R_a_b * T_a_b.linear().transpose());

  Eigen::MatrixXd J_a = solver->robot.frame_jacobian(frame_a, pinocchio::WORLD);
  Eigen::MatrixXd J_b = solver->robot.frame_jacobian(frame_b, pinocchio::WORLD);
  Eigen::MatrixXd J_ab = T_world_a.linear().transpose() * (J_b - J_a).block(3, 0, 3, solver->N);
  Eigen::MatrixXd Jlog;
  pinocchio::Jlog3(R_a_b * T_a_b.linear().transpose(), Jlog);

  A = mask.apply(Jlog * J_ab);
  b = mask.apply(error);
}`
--------------------------------------------------------------
`  auto T_world_a = get_T_world_frame(frame_a);
  auto T_world_b = get_T_world_frame(frame_b);
  auto T_a_b = T_world_a.inverse() * T_world_b;

  Eigen::MatrixXd R_world_a = T_world_a.linear();

  Eigen::MatrixXd J_a_pos = frame_jacobian(frame_a, pinocchio::LOCAL_WORLD_ALIGNED).block(0, 0, 3, model.nv);
  Eigen::MatrixXd J_a_rot = frame_jacobian(frame_a, pinocchio::LOCAL_WORLD_ALIGNED).block(3, 0, 3, model.nv);
  Eigen::MatrixXd J_b_pos = frame_jacobian(frame_b, pinocchio::LOCAL_WORLD_ALIGNED).block(0, 0, 3, model.nv);

  return (R_world_a.transpose() * (J_b_pos - J_a_pos) +
          pinocchio::skew(T_a_b.translation()) * R_world_a.transpose() * J_a_rot);
`


Thank you very much .

**Comment by Gregwar** [comment]
Ok, I started writing something here, currently covering only for the relative orientation:

https://gregwar.github.io/jacobians

Please tell me if it's understandable. If it is, I will add the derivation for relative position as well.

**Comment by kassasin** [comment]
yes,thank you very much .i have understand this blog. i noticed  this in code :
`Eigen::MatrixXd J_ab = T_world_a.linear().transpose() * (J_b - J_a).block(3, 0, 3, solver->N);
`
but i still dont understand this ：
`pinocchio::Jlog3(R_a_b * T_a_b.linear().transpose(), Jlog);`

**Comment by Gregwar** [comment]
Suppose the orientation of an effector is in the current configuration $R_0$, and you want to take it to the desired configuration $R_1$

By applying a space  angular velocity $\omega$, the resulting configuration will be $R = exp3(\omega) R_0$, where the $exp3$ operator refers to the exponent of the screw symmetric matrix associated to $\omega$

You then want the following to hold:

$$exp3(\omega) R_0 = R_1$$

To achieve this motion, you need to have

$$\omega = log3(R_1 R_0^T)$$

Where log3 is the opposite operator of exp3 (mapping a matrix to a vector of dimension 3).
You can use the pseudo-inverse of the Jacobian to try to achieve this $\omega$, but you might end up achieving another $\omega'$ (e.g if the task is overconstrained). In that case, the pseudo-inverse is equivalent to minimizing the error $|| \omega' - \omega ||^2$.

Somehow, this is fine because you try to get as close as possible to the desired $\omega$. However, this is not an euclidian space, so it seems ill-defined to use the squared norm as an error function.

---

Another way of defining the problem is:

$$
log3(R_0 R_1^T exp3(\omega)) = 0
$$

We want to have the log of the residual error to be 0. Else, we would like it to be minimized. If we were to take two candidates $\omega'$ through this expression, the one with the lowest norm would this time indeed be the closest in term of orientation error.

Using Pinocchio's [Jlog3](https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/namespacepinocchio.html#a756cdb33ab783f34248c45d08aef00f4), we can take the first order approximation of the above expression as:

$$
log3(R_0 R_1^T exp3(\omega))
\approx
log3(R_0 R_1^T)
+
Jlog3(R_0 R_1^T)
\omega
$$

By using the fact that $-log(R) = log(R^{-1})$, we can write our first-order approximation objective equality to:

$$ Jlog3(R_0 R_1^T) \omega = log3(R_1 R_0^T)$$

It match the first formulation, except for a left multiplication of our velocity with the $Jlog3$ term.

---

Stéphane Caron (ping @stephane-caron ) wrote a blog post specifically about this:
https://scaron.info/robotics/jacobian-of-a-kinematic-task-and-derivatives-on-manifolds.html

I overall recommend you his blog as source of information as well :slightly_smiling_face:

**Comment by Gregwar** [comment]
As a more intuitive example, suppose you want to rotate by 1 rad about the x axis.
We compare the rotations $\omega_1 = [0.9, 0, 0]$ and $\omega_2 = [1.0, 0.1, 0.0]$.

In term of squared norm, both are producing the same error ($0.1^2$)

However, if you calculate:

```python
import numpy as np
import pinocchio as pin

np.linalg.norm(pin.log3(R.T @ pin.exp3(np.array([0.9, 0., 0]))))
# 0.1

np.linalg.norm(pin.log3(R.T @ pin.exp3(np.array([1.0, 0.1, 0])))
# 0.0958...
```

In other words, less radians will be remaining from $[1.0, 0.1, 0]$ to reach the target.

**Comment by kassasin** [comment]
thank you very much .I totally Understanded.If you have finished “relative position task” related blog,please let me know,sincerely thanks。

**Comment by kassasin** [comment]
Thank you very much, I completely understand this problem. I'm an amateur robotics enthusiast trying to do some small personal projects. I have paid attention to robot projects like ocs2 and drake before, but these libraries are too big and not well understood by me. I noticed placo by chance. It is simple and precise, and it supports python and c++, which is friendly to me. Great job.

**Comment by stephane-caron** [comment]
Nice discussion :slightly_smiling_face: Going back to the original question, you can also find some material on the extension to poses (coupled position-orientation) rather than orientation:

> Is there any math detail?for example ,how to get relative orientation task jacobian in kinetic and dynamic problem?

The discussion above is about the _relative orientation_ task Jacobian in $SO(3)$, and the [blog post](https://scaron.info/robotics/jacobian-of-a-kinematic-task-and-derivatives-on-manifolds.html) linked above by @Gregwar is about the same for poses in $SE(3)$.

The _relative pose_ task Jacobian in $SE(3)$ can be derived in a similar way: @ymontmarin wrote this down in the documentation of [`RelativeFrameTask.compute_jacobian`](https://stephane-caron.github.io/pink/tasks.html#pink.tasks.relative_frame_task.RelativeFrameTask.compute_jacobian) in Pink (another IK library implemented in Python and cousin to PlaCo).
