### ISSUE TITLE
Manipulability

### ISSUE THREAD

**Issue by Gregwar** [Rhoban/placo#4]
As suggested by @kassasin we could have a task for manipulability

https://github.com/Rhoban/placo-examples/issues/1#issuecomment-2162053028

**Comment by Gregwar** [comment]
In this work, they also refer to using such task:
https://m.youtube.com/watch?v=YQ0_Gy3DetQ

I believe derivations are provided in associated paper

**Comment by Gregwar** [comment]
I think we could have a task trying to get a condition number as close as possible to 1

**Comment by Gregwar** [comment]
We use Quadratic Programming as a backend, so we can't add non-convex tasks. For example, maximizing the volume of the manipulability ellipsoid is not a valid task since it is not bounded

Trying to bring the condition number of JJ^T to 1 seems however a valid task, all it takes is deriving the first order approximation of this condition number with respect to the dofs

**Comment by kassasin** [comment]
in this [blog,](https://jhavl.github.io/mmc/)they said"The manipulability measure has a complex non-linear relationship with the robot’s joint configuration and in this paper we derive the manipulability Jacobian which directly relates joint velocities to the rate of change of manipulability. Furthermore, we use the manipulability Jacobian within a constrained quadratic program to create an improved resolved-rate motion controller for redundant robots. The resulting real-time controller provides joint velocities which achieve a desired Cartesian end-effector velocity while also maximising the robot’s manipulability"
In their paper,they add a linear term in qp problem in order to maxmise manipulabiliby
![截图_2024-06-12_16-27-35](https://github.com/Rhoban/placo-examples/assets/26887176/02c8c563-3918-4d25-abef-3cedea3bdbe3)
Jm represent manipulabiliby jacobian .
Is it helpful?

**Comment by Gregwar** [comment]
I see, they only use first order approx here, it is not a proper task since it has no hessian, but it should be a good regularization term

**Comment by Gregwar** [comment]
We would need to compute this guy, I might give it a try someday
Do you have some project involving redundancy and lack of regularization where you could test a solution ?

![Screenshot_20240612-153921](https://github.com/Rhoban/placo/assets/367022/9259fdbe-5219-401d-a95a-8a9161d4bacd)

**Comment by Gregwar** [comment]
I made a first implementation on the [manipulability branch](https://github.com/Rhoban/placo/compare/master...manipulability)

**Comment by kassasin** [comment]
@Gregwar Yes，I just try to control seven freedom manipulator,I found the manipulability always small when I  only try to track end effector.I also have an idea wether we can track manipulability ellipsoid when we do other job.In this way we can use some other method to learn manipulability ellipsoid from demonstration and track it when control robot .

**Comment by Gregwar** [comment]
I added the `ManipulabilityTask` in the latest release

See: https://placo.readthedocs.io/en/latest/kinematics/regularization.html#manipulability-regularization
Do not hesitate to ping me if you give it a try!
